<?php

namespace RM\DiscretasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRepository extends EntityRepository
{
    /**
     * Devuelve todos los tipos de variables menos RFM
     *
     * @return Tipo[]
     */
    public function findTipoSegmentador()
    {
        $tipos = $this->createQueryBuilder('tipo')
            ->where('tipo.codigo != :codigo_RFM')
            ->setParameter('codigo_RFM', Tipo::RFM)
            ->getQuery()
            ->getResult();

        return $tipos;
    }
}
