parameters:
    variablesDiscretas.class: RM\DiscretasBundle\DependencyInjection\Discreta
    configuracion.class: RM\DiscretasBundle\DependencyInjection\ConfiguracionService

services:
    variablesDiscretas:
        class: %variablesDiscretas.class%
        arguments: [@rm.manager]
    
    configuracion:
        class: %configuracion.class%
        arguments: [@rm.manager]

    rm_discretas.personaliza_variable_discreta:
        class: RM\DiscretasBundle\DependencyInjection\PersonalizaVariableDiscreta
        arguments: [@rm.manager]
        
    #Para borra despues pbdespues
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags: [{ name: 'twig.extension' }]

