
services:
    rm.comunicacion.manager:
        class: RM\ComunicacionBundle\DomainManager\ComunicacionManager
        arguments:
            - @rm.manager
            - @event_dispatcher
            - @validator
