direct_homepage:
  path: /monitor/
  defaults: {_controller: RMComunicacionBundle:Instancia:showInstancias, idOpcionMenuIzq 2 }
  methods: [GET]
  
direct_manager:
  path: /manager/
  defaults: {_controller: RMComunicacionBundle:Comunicacion:index}
  methods: [GET|POST]
  

direct_manager_delete:
  path: /manager/delete/
  defaults: {_controller: RMComunicacionBundle:Comunicacion:deleteComunicaciones}
  methods: [POST]
  
direct_manager_new:
  path: /manager/new/
  defaults: {_controller: RMComunicacionBundle:Comunicacion:new}
  methods: [GET|POST]

direct_manager_parar_comunicacion:
  path: /manager/comunicacion/{idComunicacion}/stop
  defaults: {_controller: RMComunicacionBundle:Comunicacion:parar}
  methods: [POST]
  requirements:
    idComunicacion: \d+

direct_manager_reanudar_comunicacion:
  path: /manager/comunicacion/{idComunicacion}/restart
  defaults: { _controller: RMComunicacionBundle:Comunicacion:reanudar }
  methods: [POST]
  requirements:
    idComunicacion: \d+
  
direct_manager_edit_datos:
  path: /manager/comunicacion/{idComunicacion}/
  defaults: {_controller: RMComunicacionBundle:Comunicacion:edit}
  requirements:
    idComunicacion: \d+

rm_comunicacion.comunicacion.editar_plantilla:
  path: /manager/comunicacion/{idComunicacion}/plantilla
  defaults: {_controller: RMComunicacionBundle:Comunicacion:editPlantillaComunicacion}
  requirements:
      idComunicacion: \d+


direct_monitor:
  path: /monitor/
  defaults: {_controller: RMComunicacionBundle:Instancia:showInstancias, idOpcionMenuIzq 2 }
  methods: [GET]
  
direct_monitor_actualizar:
  path: /monitor/
  defaults: {_controller: RMComunicacionBundle:Instancia:actualizarListadoInstancias}
  methods: [POST]
  
direct_monitor_controlador_fases:
  path: /monitor/instance/{id_instancia}/
  defaults: {_controller: RMComunicacionBundle:Instancia:controladorVistasFaseInstancias}
  requirements:
    id_instancia: \d+

direct_monitor_cambio_fase:
  path: /monitor/instance/{id_instancia}/cambiofase
  defaults: {_controller: RMComunicacionBundle:Instancia:cambioFase}
  methods: [POST]
  requirements:
    id_instancia: \d+

direct_monitor_fase_conf_criterios:
  path: /monitor/instance/{id_instancia}/criterios
  defaults: {_controller: RMComunicacionBundle:Instancia:controladorFaseConfCriterios}
  methods: [GET]
  requirements:
    id_instancia: \d+
    
direct_monitor_fases_avisos:
  path: /monitor/instance/avisos/{listaCatNeeded}
  defaults: {_controller: RMComunicacionBundle:Instancia:fichaAvisos}
  methods: [GET]
  
direct_monitor_enviar_avisos:
  path: /monitor/instance/avisos/envioAvisos
  defaults: {_controller: RMComunicacionBundle:Instancia:envioAvisos}
  methods: [POST] 
  
direct_monitor_show_avisos:
   path: /monitor/instance/avisos/show/{objUsers}/{contador}
   defaults: {_controller: RMComunicacionBundle:Instancia:showFichaAviso}
   methods: [POST]
   requirements:
    objUsers: \d+
    contador: \d+
    
direct_monitor_finalizar:
   path: /monitor/instance/finalizar/{id_instancia}
   defaults: {_controller: RMComunicacionBundle:Instancia:finalizarInstancias}
   methods: [POST]
   requirements:
    id_instancia: \d+
    
direct_monitor_preview:
   path: monitor/instance/preview/{id_instancia}
   defaults: {_controller: RMComunicacionBundle:Instancia:previewComunicaciones}
   requirements:
    id_instancia: \d+
    
direct_actualizar_tabla_consumidores:
   path: monitor/instance/preview/actualizar/{id_instancia}
   defaults: {_controller: RMComunicacionBundle:Instancia:actualizarTablaConsumidores}
   methods: [POST]
   requirements:
    id_instancia: \d+ 

direct_datos_promo_consumidores:
   path: monitor/instance/preview/{id_instancia}/promo/{id_cliente}/
   defaults: {_controller: RMComunicacionBundle:Instancia:showPreviewPromo}
   methods: [GET]
   requirements:
    id_cliente: \d+  
    

direct_getting_consumers:
   path: monitor/manager/instance/{id_instancia}/getting_consumers
   defaults: {_controller: RMComunicacionBundle:Instancia:gettingConsumers}
   methods: [POST]

rm_comunicacion.segmento_comunicacion.reanudar_segmento:
   path: direct/manager/reanudar/segmentocomunicacion/{idSegmentoComunicacion}/
   defaults: {_controller: RMComunicacionBundle:SegmentoComunicacion:reanudarSegmentoComunicacion}
   methods: [POST]
   requirements:
      idSegmentoComunicacion: \d+

rm_comunicacion.segmento_comunicacion.parar_segmento:
   path: direct/manager/parar/segmentocomunicacion/{idSegmentoComunicacion}/
   defaults: {_controller: RMComunicacionBundle:SegmentoComunicacion:pararSegmentoComunicacion}
   methods: [POST]
   requirements:
      idSegmentoComunicacion: \d+

rm_comunicacion.segmento_comunicacion.eliminar_segmento:
   path: direct/manager/eliminar/segmentocomunicacion/{idSegmentoComunicacion}/
   defaults: {_controller: RMComunicacionBundle:SegmentoComunicacion:eliminarSegmentoComunicacion}
   methods: [POST]
   requirements:
      idSegmentoComunicacion: \d+

rm_comunicacion.comunicacion.index:
  path: /direct/manager/comunicacion/index
  defaults: { _controller: RMComunicacionBundle:Comunicacion:index }

rm_comunicacion.comunicacion.asigna_nueva_plantilla:
   path: /data/comunicacion/{id_comunicacion}/asigna/plantilla
   defaults: { _controller: RMComunicacionBundle:Comunicacion:asignaNuevaPlantilla }
   methods: [GET]
   requirements:
     id_comunicacion: \d+
