parameters:
    variablesTransformadas.class: RM\TransformadasBundle\DependencyInjection\Transformada



services:
    variablesTransformadas:
        class: %variablesTransformadas.class%
        arguments: [@rm.manager]
        
    #Para borra despues pbdespues
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags: [{ name: 'twig.extension' }]
