Campaign_homepage:
  path: /
  defaults: {_controller: RMComunicacionBundle:Campaign:showCampanyas, idOpcionMenuIzq 1, closing 0 }
  methods: [GET]

campaign_campanyas:
  path: /list/
  defaults: {_controller: RMComunicacionBundle:Campaign:showCampanyas, idOpcionMenuIzq 1, closing 0 }
  methods: [GET]

campaign_ficha:
  path: /show/{id_instancia}
  defaults: {_controller: RMComunicacionBundle:Campaign:show, idOpcionMenuIzq 1 }
  methods: [GET]
  requirements:
    id_instancia: \d+

campaign_redirect:
  path: /list/
  defaults: {_controller: RMComunicacionBundle:Campaign:showCampanyas, idOpcionMenuIzq 1 }
  methods: [GET]

campaign_closing_campanyas:
  path: /list/closing_campaigns/
  defaults: {_controller: RMComunicacionBundle:Campaign:showClosingCampaigns, idOpcionMenuIzq 2, closing 1}
  methods: [GET]

campaign_closing_ficha:
  path: /list/closing/{id_instancia}/{id_categoria}
  defaults: {_controller: RMComunicacionBundle:Campaign:fichaClosingCampanya, idOpcionMenuIzq 1 }
  methods: [GET]
  requirements:
    id_categoria: \d+
    id_instancia: \d+

campaign_creatividades:
   path: /creatividades/list
   defaults: { _controller: RMComunicacionBundle:Campaign:listaCreatividades, idOpcionMenuIzq 3 }


campaign_seguimiento:
  path: /seguimiento
  defaults: { _controller: RMComunicacionBundle:Seguimiento:index }

campaign_productos_marca:
  path: /seguimiento/productos/
  defaults: { _controller: RMComunicacionBundle:Seguimiento:obtenerProductosPorMarca }
  methods: [GET]

rm_comunicacion.campaign.show_campaing_creatividades:
  path: /creatividad/show/{id_instancia}
  defaults: { _controller: RMComunicacionBundle:Campaign:showCampaignCreatividades }
  methods: [GET]
  requirements:
    id_instancia: \d+

