services:
  mongoservice:
    class: RM\RMMongoBundle\DependencyInjection\MongoService
    arguments: [@security.token_storage, %rm_mongo%]
    abstract: true

  rm.mongo.calcula_poblacion:
    class: RM\RMMongoBundle\DependencyInjection\CalculaPoblacionService
    parent: "mongoservice"

  rm.mongo.estadisticas_clientes:
    class: RM\RMMongoBundle\DependencyInjection\EstadisticasClientes
    parent: "mongoservice"

  rmmongo_manager_instancia_cliente:
    class: RM\RMMongoBundle\DependencyInjection\ManagerInstanciaComunicacionCliente
    arguments: [@rm.manager, @rm.mongo_manager]