parameters:
    database_driver: pdo_mysql
    database_host: 192.168.100.228
    database_port: null
    database_name: 3
    database_user: admin
    database_password: icca
    mailer_transport: gmail
    mailer_host: smtp.gmail.com
    mailer_user: imsodelicioso@gmail.com
    mailer_password: deliciosoChorong0
    locale: es
    secret: 62d1128580afcf48caa0240078ed076f70b5df19
    database_procesos_driver: pdo_mysql
    database_procesos_host: localhost
    database_procesos_port: null
    database_procesos_name: procesos
    database_procesos_user: root
    database_procesos_password:


