parameters:
    SegmentoService.class: RM\SegmentoBundle\DependencyInjection\SegmentoServicio

services:
    SegmentoService:
        class: %SegmentoService.class%
        arguments: [@rm.manager]

    rm_segmentobundle.buscadorsegmentos:
        class: RM\SegmentoBundle\DependencyInjection\BuscadorSegmentos
        arguments: [ @SegmentoService, @MarcaService, @categoriaService, @rm.manager ]