parameters:
    categoriaService.class: RM\CategoriaBundle\DependencyInjection\CategoriaServicio


services:
    categoriaService:
        class: %categoriaService.class%
        arguments: [@rm.manager, @security.token_storage, @security.authorization_checker]

    rm_categoria.cambia_asocicion_categorias:
        class: RM\CategoriaBundle\EventListener\CambiaAsociacionListener
        tags:
          - { name: doctrine.event_listener, event: postUpdate}
