<?php

namespace RM\RMMongoBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ClienteSegmentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteSegmentoRepository extends DocumentRepository
{

    public function findClientesEnSegmentos($in = [], $notIn = [])
    {
        return $this->createQueryBuilder('RMMongoBundle:ClienteSegmento')
            ->field('segmento')->in($in)
            ->field('segmento')->notIn($notIn)
            ->getQuery()
            ->execute();
    }

    public function findNumeroClientesEnSegmento($segmento)
    {
        return $this->createQueryBuilder('RMMongoBundle:ClienteSegmento')
            ->field('segmento')->in($segmento)
            ->count()
            ->getQuery()
            ->execute();
    }

    public function findNumeroClientesEnSegmentos($in = [], $notIn = [])
    {
        return $this->createQueryBuilder('RMMongoBundle:ClienteSegmento')
            ->field('segmento')->in($in)
            ->field('segmento')->notIn($notIn)
            ->count()
            ->getQuery()
            ->execute();
    }

    public function findClientes($condicion)
    {
        $clientes = $this->createQueryBuilder()
            ->hydrate(false)
            ->distinct('cli')
            ->setQueryArray($condicion)
            ->getQuery()->execute();

        return iterator_to_array($clientes);
    }


}
