<?php

namespace RM\RMMongoBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ResultadoClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoClienteRepository extends DocumentRepository
{
    public function findMesesDisponibles()
    {
        $meses = $this->createQueryBuilder()
            ->distinct('fecha')
            ->sort('fecha', 'desc')
            ->getQuery()->execute();

        $meses = iterator_to_array($meses);
        $meses = array_reverse($meses);

        $resultado = [];

        foreach ($meses as $mes) {
            if (is_null($mes)) {
                continue;
            }

            list($year, $month) = explode('-', $mes);
            $resultado[]        = [
                'id'    => $mes,
                'fecha' => new \DateTime(sprintf('01-%s-%s', $month, $year))
            ];
        }
        return $resultado;
    }
}