<?php

namespace RM\RMMongoBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * ResultadoMensualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoMensualRepository extends DocumentRepository
{
    /**
     * Devuelve el listado de meses en orden descendente
     * De más nuevo, a mas antiguo
     *
     * @return array
     */
    public function findMesesDisponibles($from = null)
    {
        $qb = $this->dm
            ->createQueryBuilder('RMMongoBundle:ResultadoMensual')
            ->hydrate(false)
            ->select('id')
            ->sort('id', 'desc');

        if($from instanceof \DateTime) {
            $qb->where("function() { return this.id <= '{$from->format('Y-m')}'; }");
        }

        $meses = $qb
            ->getQuery()
            ->execute();

        $resultado = [];

        foreach($meses as $mes) {
            if (is_null($mes['_id'])) {
                continue;
            }

            list($year, $month) = explode('-', $mes['_id']);
            $resultado[] = [
                'id' => $mes['_id'],
                'fecha' => new \DateTime(sprintf('01-%s-%s', $month, $year))
            ];
        }

        return $resultado;
    }

    /**
     * Devuelve los 12 ultimos meses en orden ascendente.
     *
     * @return array
     */
    public function find12UltimosMeses($from = null)
    {
        if($from instanceof \DateTime ) {
            $mesAnterior = $from;
        } else {
            $fecha =  new \DateTime();
            $mesAnterior = $fecha->sub(new \DateInterval('P1M'));
        }


        $meses = $this->dm->createQueryBuilder('RMMongoBundle:ResultadoMensual')
            ->hydrate(true)
            ->field('id')->lte($mesAnterior->format('Y-m'))
            ->sort('id', 'desc')
            ->limit(13)
            ->getQuery()
            ->execute();

        return array_reverse(iterator_to_array($meses));
    }
}