<?php

namespace RM\RMMongoBundle\Document;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ResultadoMensualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadoMensualRepository extends DocumentRepository
{
    /**
     * Devuelve el listado de meses en orden descendente
     * De más nuevo, a mas antiguo
     *
     * @return array
     */
    public function findMesesDisponibles()
    {
        $meses = $this->dm->createQueryBuilder('RMMongoBundle:ResultadoMensual')
            ->hydrate(false)
            ->select('id')
            ->sort('id', 'desc')
            ->getQuery()
            ->execute();

        $resultado = array();

        foreach($meses as $mes) {
            if (is_null($mes['_id'])) {
                continue;
            }

            list($year, $month) = explode('-', $mes['_id']);
            $resultado[] = [
                'id' => $mes['_id'],
                'fecha' => new \DateTime(sprintf('01-%s-%s', $month, $year))
            ];
        }

        return $resultado;
    }

    /**
     * Devuelve los 12 ultimos meses en orden ascendente.
     *
     * @return array
     */
    public function find12UltimosMeses()
    {
        $fecha = new \DateTime();
        $mesAnterior = $fecha->sub(new \DateInterval('P1M'));

        $meses = $this->dm->createQueryBuilder('RMMongoBundle:ResultadoMensual')
            ->hydrate(true)
            ->field('id')->lte($mesAnterior->format('Y-m'))
            ->sort('id', 'desc')
            ->limit(13)
            ->getQuery()
            ->execute();

        return array_reverse(iterator_to_array($meses));
    }
}