<?php

namespace RM\ProcesosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoRepository extends EntityRepository
{
    /**
     * @return Proceso[]
     */
    public function findProcesosCreadosOEnProceso()
    {
        return $this->createQueryBuilder('p')
            ->join('p.tipoProceso', 'tipo')
            ->join('p.estadoProceso', 'estado')
            ->where('estado.codigo IN (:estados)')
            ->andWhere('tipo.codigo = :tipo')
            ->setParameter('tipo', TipoProceso::P00)
            ->setParameter('estados', [EstadoProceso::ESTADO_CREADO, EstadoProceso::ESTADO_EN_PROCESO])
            ->getQuery()
            ->getResult();
    }

}
