<?php

namespace RM\ProcesosBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoProcesoRepository extends EntityRepository
{
}
