
direct_config_listado_productos:
  path: /config/products/list/
  defaults: {_controller: RMProductoBundle:Producto:showProductos, idOpcionMenuIzq 3 , opcionMenuTabConfig 1 }

direct_config_listado_productos_paginador:
  path: /config/products/list/{id_categoria}/{id_marca}/{codigo}/{nombre}/
  defaults: {_controller: RMProductoBundle:Producto:showProductos, idOpcionMenuIzq 3 , opcionMenuTabConfig 1, codigo -1, nombre -1 }
  requirements:
    id_categoria: -?\d+
    id_marca: -?\d+

direct_config_listado_productos_actualizar:
  path: /config/products/list/update/
  defaults: {_controller: RMProductoBundle:Producto:actualizarProductos}
  methods: [POST]
  
direct_config_ficha_productos:
  path: /config/products/list/product/{cod_sku}/
  defaults: {_controller: RMProductoBundle:Producto:uploadImage}
  requirements:
    cod_sku: \d+

rm_producto_bundle.producto.upload_imagenes_csv:
  path: /producto/imagenes/csv/upload
  defaults: { _controller: RMProductoBundle:Producto:uploadCsvImages }

rm_producto.producto.exportar_csv_producto_sin_imagenes:
  path: /producto/export/csv
  defaults: { _controller: RMProductoBundle:Producto:exportProductosSinImagen }
  methods: [GET]

rm_producto.producto.descargar_instrucciones:
  path: /productos/instrucciones/imagenes
  defaults: { _controller: RMProductoBundle:Producto:descargarInstrucciones }
  methods: [GET]
