parameters:
    marcaService.class: RM\ProductoBundle\DependencyInjection\MarcaServicio
    PromocionService.class: RM\ProductoBundle\DependencyInjection\PromocionServicio
    ProveedorService.class: RM\ProductoBundle\DependencyInjection\ProveedorServicio
    TwigExtensionService.class: RM\ProductoBundle\Twig\Extension\TwigExtension

services:
    MarcaService:
        class: %marcaService.class%
        arguments: [@rm.manager]
        
    PromocionService:
        class: %PromocionService.class%
        arguments: [@rm.manager]

    ProveedorService:
        class: %ProveedorService.class%
        arguments: [@rm.manager]

    promocion.voucher.generator:
        class: RM\ProductoBundle\DependencyInjection\VoucherGenerator
        arguments: [@rm.manager]

    rm_producto.num_promociones.manager:
        class: RM\ProductoBundle\Manager\NumPromocionesManager
        arguments: [@rm.manager, @event_dispatcher, @validator]

    rm_producto.num_promociones.form.handler:
        class: RM\ProductoBundle\Form\Handler\NumPromocionesEditFormHandler
        arguments: [@rm_producto.num_promociones.manager]


        
    rm.twig_extension:
        class: %TwigExtensionService.class%
        tags:
            - { name: twig.extension }
