parameters:
#    rm_variables_int_discretas.example.class: RM\Variables\IntDiscretasBundle\Example

services:
#    rm_variables_int_discretas.example:
#        class: %rm_variables_int_discretas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
