rm_insight_homepage:
    path:     /index
    defaults: { _controller: RMInsightBundle:Default:index }

rm_insight_performance:
    path:     /performance
    defaults: { _controller: RMInsightBundle:Default:performance }

rm_insight_evolution:
    path:     /evolution
    defaults: { _controller: RMInsightBundle:Default:evolution}
    
rm_insight_cliente_activo:
    path:     /index/activo
    defaults: { _controller: RMInsightBundle:Default:clienteActivo }
rm_insight_cliente_inactivo:
    path: /index/inactivo
    defaults: {_controller: RMInsightBundle:Default:clienteInactivo }

rm_insight_cliente_activo_detalle:
    path:     /index/activo/detalle
    defaults: { _controller: RMInsightBundle:Default:clienteActivoDetalle, idOpcionMenuSup 4, idOpcionMenuIzq 1}
    
rm_insight_cliente_new:
    path:     /index/new
    defaults: { _controller: RMInsightBundle:Default:clienteNew, idOpcionMenuSup 4, idOpcionMenuIzq 1}
    
rm_insight_categoria:
    path:     /categoria
    defaults: { _controller: RMInsightBundle:Default:categorias, idOpcionMenuSup 4, idOpcionMenuIzq 4}

rm_insight_campaign:
    path:     /campaign
    defaults: { _controller: RMInsightBundle:Default:campaign, idOpcionMenuSup 4, idOpcionMenuIzq 5}
       
rm_insight_proveedores:
    path:     /proveedores
    defaults: { _controller: RMInsightBundle:Default:proveedores, idOpcionMenuSup 4, idOpcionMenuIzq 6}

