#Todas las rutas tiene el prefijo /data por delante, que viene heredado del fichero routing del app

rm_variables_lineales_homepage:
  path: /
  defaults: {_controller: RMCategoriaBundle:Default:showCategoriasBasicas, idOpcionMenuIzq 1}
  
data_avanced_rfm:
  path: /avanced/rfm/
  defaults: {_controller: RMLinealesBundle:Default:obtenerRegistros, tipoVar 1, idOpcionMenuIzq 4}

data_avanced:
  path: /avanced/
  defaults: {_controller: FrameworkBundle:Redirect:redirect, route: data_avanced_rfm}
 
data_avanced_sociodemografico:
  path: /avanced/sociodemographic/
  defaults: {_controller: RMLinealesBundle:Default:obtenerVariablesSociodemograficas, tipoVar 4, idOpcionMenuIzq 7}

data_informacion_variable:
  path: /avanced/sociodemographic/{idVariable}/
  defaults: { _controller: RMLinealesBundle:Default:muestraInformacionVariable, idOpcionMenuIzq 7 }


