parameters:
    PlantillaService.class: RM\PlantillaBundle\DependencyInjection\PlantillaServicio

    TamanyoImagenService.class: RM\PlantillaBundle\DependencyInjection\TamanyoImagenServicio

services:
    PlantillaService:
        class: RM\PlantillaBundle\DependencyInjection\PlantillaServicio
        arguments: [@doctrine]

    TamanyoImagenService:
        class: %TamanyoImagenService.class%
        arguments: [@rm.manager]

    GrupoSlotService:
        class: RM\PlantillaBundle\DependencyInjection\GrupoSlotsServicio
        arguments: [@doctrine]


    rm_plantilla.elimina_grupo_slots:
      class: RM\PlantillaBundle\EventListeners\EliminaGruposSlotsListener
      arguments: [@rm.grupo_slot_manager]
      tags:
        - { name: kernel.event_listener, event: rm_plantilla.eliminar_plantilla, method: onPlantillaEliminada }

    rm_plantilla.elimina_slots:
      class: RM\PlantillaBundle\EventListeners\EliminaSlotsListener
      arguments: [@doctrine]
      tags:
        - { name: kernel.event_listener, event: rm_plantilla.eliminar_grupo_slots, method: onGrupoSlotsEliminado}

    rm_plantilla.crea_slots:
      class: RM\PlantillaBundle\EventListeners\CreaSlotsListener
      arguments: [@doctrine]
      tags:
        - { name: kernel.event_listener, event: rm_plantilla.nuevo_grupo_slots, method: onNuevoGrupoSlot }

    rm_plantilla_genera_plantilla_comunicacion:
      class: RM\PlantillaBundle\DependencyInjection\GeneraPlantillaComunicacion
      arguments: [@twig, %web_path%, @security.context]

    rm_plantilla.form.tamanyoImagen:
      class: RM\PlantillaBundle\Form\TamanyoImagen\TamanyoImagenType
      tags:
        - { name: form.type, alias: tamanyoImagen }

    rm_plantilla.modifica_num_slots:
      class: RM\PlantillaBundle\EventListeners\ModificaNumeroSlotsListener
      tags:
        - { name: doctrine.event_listener, event: postUpdate}

    rm_plantilla.importacion_exportacion_plantillas:
      class: RM\PlantillaBundle\DependencyInjection\ImportacionExportacionPlantilla
      arguments: [@doctrine, @event_dispatcher]

    rm_plantilla.email_parser:
      class: RM\PlantillaBundle\Parsers\EmailParser
      arguments: [@rm_plantilla_genera_plantilla_comunicacion, @rmmongo_manager_instancia_cliente]

    rm.plantilla_manager:
      class: RM\PlantillaBundle\DomainManager\PlantillaManager
      arguments: [@doctrine, @event_dispatcher]

    rm.grupo_slot_manager:
      class: RM\PlantillaBundle\DomainManager\GrupoSlotManager
      arguments: [@doctrine, @event_dispatcher]


    rm_plantilla.create_plantilla_form_handler:
      class: RM\PlantillaBundle\Form\Handler\CreatePlantillaFormHandler
      arguments: [@rm.plantilla_manager]

    rm.create_grupo_slot_form_handler:
      class: RM\PlantillaBundle\Form\Handler\CreateGrupoSlotFormHandler
      arguments: [@rm.grupo_slot_manager, @form.factory]